#==============================================================================#
#' Calculate MACCS fingerprints for a set of molecules
#'
#' @description
#'   Calculate MACCS (Molecular ACCess System) fingerprints for a set of
#'   molecules. Each fingerprint is a fixed-length binary vector representing
#'   the presence or absence of predefined structural features.
#'
#'   The fingerprints are calculated using the \code{GetMACCSKeysFingerprint()}
#'   function from the \code{rdMolDescriptors} module in RDKit.
#'
#'   Invalid molecules are represented by \code{NA} vectors. Row order is
#'   preserved so that the output aligns with the input.
#'
#' @param mols
#'   A character vector of SMILES or InChI strings, or a list of RDKit
#'   Mol objects.
#' @inheritParams ParseMolecules
#'
#' @return
#'   A matrix of integers (0/1) with one row per molecule and one column per
#'   MACCS key (length 167). Rows corresponding to invalid molecules contain
#'   \code{NA}.
#'
#'   Additionally, the \code{"valid"} attribute is attached to indicate which
#'   molecules were successfully processed.
#'
#' @examples
#'   # Calculate MACCS fingerprints
#'   smiles <- c("CCO", "c1ccccc1", "invalid_molecule")
#'   fps <- CalculateMaccsFingerprints(smiles)
#'
#'   # Get the number of fingerprints (columns)
#'   ncol(fps)
#'   #> 167
#'
#'   # Check which molecules were successfully processed
#'   attr(fps, "valid")
#'   #> TRUE TRUE FALSE
#'
#' @importFrom reticulate py
#' @importFrom reticulate py_to_r
#'
#' @export
#==============================================================================#
CalculateMaccsFingerprints <- function(mols,
                                       verbose = FALSE) {

  .EnsurePythonReady()


  #--[ Check input arguments ]--------------------------------------------------

  # 'mols'
  if ((!is.character(mols) || length(mols) == 0L) &&
      (!is.list(mols) || length(mols) == 0L ||
       (!is.null(mols[[1L]]) &&
        !inherits(mols[[1L]], "rdkit.Chem.rdchem.Mol")))) {
    stop("'mols' must be a character vector (SMILES or InChI) ",
         "or a list of RDKit Mol objects.")
  }

  # 'verbose'
  if (!is.logical(verbose) || length(verbose) != 1L) {
    stop("'verbose' must be a logical value.")
  }


  #--[ Calculate fingerprints ]-------------------------------------------------

  # rdkit.Chem.MACCSkeys.GenMACCSKeys()
  # https://rdkit.org/docs/source/rdkit.Chem.rdMolDescriptors.html
  py_obj <- reticulate::py$calculate_maccs_fps(
    as.list(mols),
    verbose = verbose
  )
  fp_size <- 167L
  fps <- t(vapply(reticulate::py_to_r(py_obj), function(a1) {
    if(is.null(a1)) {
      return(rep(NA_integer_, fp_size))
    } else {
      return(a1)
    }
  }, integer(fp_size), USE.NAMES = FALSE))
  attr(fps, "valid") <- !is.na(fps[, 1L])
  return(fps)
}



#==============================================================================#
#' Calculate RDKit topological fingerprints for a set of molecules
#'
#' @description
#'   Calculate RDKit topological (path-based) fingerprints for a set of
#'   molecules. The fingerprints are generated by enumerating linear and
#'   optionally branched subgraphs (paths) within a molecule and hashing them
#'   into a fixed-length bit vector.
#'
#'   The fingerprints are calculated using the \code{RDKFingerprint()} function
#'   from the \code{rdmolops} module in RDKit.
#'
#'   Invalid molecules are represented by \code{NA} vectors. Row order is
#'   preserved so that the output aligns with the input.
#'
#' @param mols
#'   A character vector of SMILES or InChI strings, or a list of RDKit
#'   Mol objects.
#' @param min_path
#'   An integer value. Minimum number of bonds to include in the subgraphs.
#' @param max_path
#'   An integer value. Maximum number of bonds to include in the subgraphs.
#' @param fp_size
#'   An integer value. Number of bits in the fingerprint.
#' @param n_bits_per_hash
#'   An integer value. Number of bits to set per path.
#' @param use_hydrogens
#'   A logical value. Include paths involving hydrogens in the fingerprint if
#'   the molecule has explicit hydrogens.
#' @param target_density
#'   A numeric value. Fold the fingerprint until this minimum density has been
#'   reached.
#' @param min_size
#'   An integer value. The minimum size the fingerprint will be folded to when
#'   trying to reach \code{target_density}.
#' @param branched_paths
#'   A logical value. If set, both branched and unbranched paths will be used in
#'   the fingerprint.
#' @param use_bond_order
#'   A logical value. If set, both bond orders will be used in the path hashes.
#' @inheritParams ParseMolecules
#'
#' @return
#'   A matrix of integers (0/1) with one row per molecule and \code{fp_size}
#'   columns. Rows corresponding to invalid molecules contain \code{NA}.
#'
#'   Additionally, the \code{"valid"} attribute is attached to indicate which
#'   molecules were successfully processed.
#'
#' @examples
#'   # Calculate RDKit fingerprints
#'   smiles <- c("CCO", "c1ccccc1", "invalid_molecule")
#'   fps <- CalculateRdkitFingerprints(smiles)
#'
#'   # Get the number of fingerprints (columns)
#'   ncol(fps)
#'   #> 2048
#'
#'   # Check which molecules were successfully processed
#'   attr(fps, "valid")
#'   #> TRUE TRUE FALSE
#'
#' @importFrom reticulate py
#' @importFrom reticulate py_to_r
#'
#' @export
#==============================================================================#
CalculateRdkitFingerprints <- function(mols,
                                       min_path = 1L,
                                       max_path = 7L,
                                       fp_size = 2048L,
                                       n_bits_per_hash = 2L,
                                       use_hydrogens = TRUE,
                                       target_density = 0,
                                       min_size = 128L,
                                       branched_paths = TRUE,
                                       use_bond_order = TRUE,
                                       verbose = FALSE) {

  # TODO: The 'RDKFingerprint()' function contains some additional arguments:
  #   - atomInvariants
  #   - fromAtoms
  #   - atomBits
  #   - bitInfo

  .EnsurePythonReady()


  #--[ Check input arguments ]--------------------------------------------------

  # 'mols'
  if ((!is.character(mols) || length(mols) == 0L) &&
      (!is.list(mols) || length(mols) == 0L ||
       (!is.null(mols[[1L]]) &&
        !inherits(mols[[1L]], "rdkit.Chem.rdchem.Mol")))) {
    stop("'mols' must be a character vector (SMILES or InChI) ",
         "or a list of RDKit Mol objects.")
  }

  # 'min_path'
  if (!is.numeric(min_path) || length(min_path) != 1L ||
      abs(min_path - as.integer(min_path)) > 1e-10) {
    stop("'min_path' must be an integer value.")
  }

  # 'max_path'
  if (!is.numeric(max_path) || length(max_path) != 1L ||
      abs(max_path - as.integer(max_path)) > 1e-10) {
    stop("'max_path' must be an integer value.")
  }

  # 'fp_size'
  if (!is.numeric(fp_size) || length(fp_size) != 1L ||
      abs(fp_size - as.integer(fp_size)) > 1e-10) {
    stop("'fp_size' must be an integer value.")
  }

  # 'n_bits_per_hash'
  if (!is.numeric(n_bits_per_hash) || length(n_bits_per_hash) != 1L ||
      abs(n_bits_per_hash - as.integer(n_bits_per_hash)) > 1e-10) {
    stop("'n_bits_per_hash' must be an integer value.")
  }

  # 'use_hydrogens'
  if (!is.logical(use_hydrogens) || length(use_hydrogens) != 1L) {
    stop("'use_hydrogens' must be a logical value.")
  }

  # 'target_density'
  if (!is.numeric(target_density) || length(target_density) != 1L) {
    stop("'target_density' must be a numeric value.")
  }

  # 'min_size'
  if (!is.numeric(min_size) || length(min_size) != 1L ||
      abs(min_size - as.integer(min_size)) > 1e-10) {
    stop("'min_size' must be an integer value.")
  }

  # 'branched_paths'
  if (!is.logical(branched_paths) || length(branched_paths) != 1L) {
    stop("'branched_paths' must be a logical value.")
  }

  # 'use_bond_order'
  if (!is.logical(use_bond_order) || length(use_bond_order) != 1L) {
    stop("'use_bond_order' must be a logical value.")
  }

  # 'verbose'
  if (!is.logical(verbose) || length(verbose) != 1L) {
    stop("'verbose' must be a logical value.")
  }


  #--[ Calculate fingerprints ]-------------------------------------------------

  # rdkit.Chem.rdmolops.RDKFingerprint()
  # https://rdkit.org/docs/source/rdkit.Chem.rdmolops.html
  py_obj <- reticulate::py$calculate_rdkit_fps(
    as.list(mols),
    minPath = as.integer(min_path),
    maxPath = as.integer(max_path),
    fpSize = as.integer(fp_size),
    nBitsPerHash = as.integer(n_bits_per_hash),
    useHs = use_hydrogens,
    tgtDensity = target_density,
    minSize = as.integer(min_size),
    branchedPaths = branched_paths,
    useBondOrder = use_bond_order,
    verbose = verbose
  )
  fps <- t(vapply(reticulate::py_to_r(py_obj), function(a1) {
    if(is.null(a1)) {
      return(rep(NA_integer_, fp_size))
    } else {
      return(a1)
    }
  }, integer(fp_size), USE.NAMES = FALSE))
  attr(fps, "valid") <- !is.na(fps[, 1L])
  return(fps)
}



#==============================================================================#
#' Calculate Morgan fingerprints for a set of molecules
#'
#' @description
#'   Calculate Morgan (circular) fingerprints for a set of molecules. Morgan
#'   fingerprints are generated by iteratively updating atom invariants based on
#'   neighboring atoms within a given bond radius. The resulting circular
#'   substructures are hashed into a fixed-length bit vector.
#'
#'   The fingerprints are calculated using the \code{GetMorganGenerator()}
#'   function from the \code{rdFingerprintGenerator} module in RDKit.
#'
#'   Invalid molecules are represented by \code{NA} vectors. Row order is
#'   preserved so that the output aligns with the input.
#'
#' @param mols
#'   A character vector of SMILES or InChI strings, or a list of RDKit
#'   Mol objects.
#' @param radius
#'   An integer value. Bond radius defining the size of circular substructures.
#' @param fp_size
#'   An integer value. Number of bits in the fingerprint.
#' @param count_simulation
#'   A logical value. If set, use count simulation while generating the
#'   fingerprint.
#' @param include_chirality
#'   A logical value. If set, chirality information will be added to the
#'   generated fingerprint.
#' @param use_bond_types
#'   A logical value. If set, bond types will be included as a part of the
#'   default bond invariants.
#' @param include_ring_membership
#'   A logical value. If set, whether or no.t the atom is in a ring will be used
#'   in the invariant list.
#' @inheritParams ParseMolecules
#'
#' @return
#'   A matrix of integers (0/1) with one row per molecule and \code{fp_size}
#'   columns. Rows corresponding to invalid molecules contain \code{NA}.
#'
#'   Additionally, the \code{"valid"} attribute is attached to indicate which
#'   molecules were successfully processed.
#'
#' @examples
#'   # Calculate Morgan fingerprints
#'   smiles <- c("CCO", "c1ccccc1", "invalid_molecule")
#'   fps <- CalculateMorganFingerprints(smiles)
#'
#'   # Get the number of fingerprints (columns)
#'   ncol(fps)
#'   #> 2048
#'
#'   # Check which molecules were successfully processed
#'   attr(fps, "valid")
#'   #> TRUE TRUE FALSE
#'
#' @importFrom reticulate py
#' @importFrom reticulate py_to_r
#'
#' @export
#==============================================================================#
CalculateMorganFingerprints <- function(mols,
                                        radius = 3L,
                                        fp_size = 2048L,
                                        count_simulation = FALSE,
                                        include_chirality = FALSE,
                                        use_bond_types = TRUE,
                                        include_ring_membership = TRUE,
                                        verbose = FALSE) {

  # TODO: The 'GetMorganGenerator()' function contains some additional
  # arguments:
  #   - onlyNonzeroInvariants
  #   - countBounds
  #   - atomInvariantsGenerator
  #   - bondInvariantsGenerator
  #   - includeRedundantEnvironments

  .EnsurePythonReady()


  #--[ Check input arguments ]--------------------------------------------------

  # 'mols'
  if ((!is.character(mols) || length(mols) == 0L) &&
      (!is.list(mols) || length(mols) == 0L ||
       (!is.null(mols[[1L]]) &&
        !inherits(mols[[1L]], "rdkit.Chem.rdchem.Mol")))) {
    stop("'mols' must be a character vector (SMILES or InChI) ",
         "or a list of RDKit Mol objects.")
  }

  # 'radius'
  if (!is.numeric(radius) || length(radius) != 1L ||
      abs(radius - as.integer(radius)) > 1e-10) {
    stop("'radius' must be an integer value.")
  }

  # 'fp_size'
  if (!is.numeric(fp_size) || length(fp_size) != 1L ||
      abs(fp_size - as.integer(fp_size)) > 1e-10) {
    stop("'fp_size' must be an integer value.")
  }

  # 'count_simulation'
  if (!is.logical(count_simulation) || length(count_simulation) != 1L) {
    stop("'count_simulation' must be a logical value.")
  }

  # 'include_chirality'
  if (!is.logical(include_chirality) || length(include_chirality) != 1L) {
    stop("'include_chirality' must be a logical value.")
  }

  # 'use_bond_types'
  if (!is.logical(use_bond_types) || length(use_bond_types) != 1L) {
    stop("'use_bond_types' must be a logical value.")
  }

  # 'include_ring_membership'
  if (!is.logical(include_ring_membership) ||
      length(include_ring_membership) != 1L) {
    stop("'include_ring_membership' must be a logical value.")
  }

  # 'verbose'
  if (!is.logical(verbose) || length(verbose) != 1L) {
    stop("'verbose' must be a logical value.")
  }


  #--[ Calculate fingerprints ]-------------------------------------------------

  # rdkit.Chem.rdFingerprintGenerator.GetMorganGenerator()
  # https://rdkit.org/docs/source/rdkit.Chem.rdFingerprintGenerator.html
  py_obj <- reticulate::py$calculate_morgan_fps(
    as.list(mols),
    radius = as.integer(radius),
    fpSize = as.integer(fp_size),
    countSimulation = count_simulation,
    includeChirality = include_chirality,
    useBondTypes = use_bond_types,
    includeRingMembership = include_ring_membership,
    verbose = verbose
  )
  fps <- t(vapply(reticulate::py_to_r(py_obj), function(a1) {
    if(is.null(a1)) {
      return(rep(NA_integer_, fp_size))
    } else {
      return(a1)
    }
  }, integer(fp_size), USE.NAMES = FALSE))
  attr(fps, "valid") <- !is.na(fps[, 1L])
  return(fps)
}


